=== totttte/toteme/data/menu.dtd
<!ELEMENT mainmenu (menu*)>
 <!ELEMENT menu (name,(submenu|separator|menu)*)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT separator EMPTY>
 <!ELEMENT submenu (#PCDATA)>
   <!ATTLIST submenu method CDATA #REQUIRED>
   <!ATTLIST submenu enabled CDATA #IMPLIED>

=== totttte/toteme/data/mainmenu.xml
<?xml version="1.0" encoding="Shift_JIS" ?>
<!DOCTYPE mainmenu SYSTEM "menu.dtd">

<mainmenu>
 <menu>
  <name>ファイル(F)</name>
  <submenu method="signout">サインアウト</submenu>
  <submenu method="changestatus">状態変更</submenu>
  <submenu method="changename">名前変更</submenu>
  <submenu method="changePSM">パーソナルメッセージ変更</submenu>
  <separator />
  <submenu method="closed">終了</submenu>
 </menu>
 <menu>
  <name>編集(E)</name>
  <submenu method="changeIcon" enabled="false">表示アイコンの変更</submenu>
  <submenu method="instantmessage">インスタントメッセージの送信</submenu>
  <separator />
 </menu>
 <menu>
  <name>書式(O)</name>
  <submenu method="toSimple">より画面をシンプルにする</submenu>
  <submenu method="bunrui">メンバを一覧で表示する</submenu>
 </menu>
 <menu>
  <name>表示(V)</name>
  <submenu method="option" enabled="false">オプション</submenu>
 </menu>
 <menu>
  <name>ヘルプ(H)</name>
  <submenu method="version">バージョン情報</submenu>
 </menu>
</mainmenu>

=== totttte/toteme/data/chatmenu.xml
<?xml version="1.0" encoding="Shift_JIS" ?>
<!DOCTYPE mainmenu SYSTEM "menu.dtd">

<mainmenu>
 <menu>
  <name>ファイル(F)</name>
  <submenu method="save">会話ログを保存</submenu>
  <separator />
  <submenu method="closed">このウィンドウを閉じる</submenu>
 </menu>
 <menu>
  <name>編集(E)</name>
  <submenu method="invite">誰かを招待</submenu>
  <separator />
  <submenu method="myFont">自分のフォント</submenu>
 </menu>
 <menu>
  <name>書式(O)</name>
  <submenu method="chatFont">送信済みエリアを白黒/カラーに変更する</submenu>
  <submenu method="toSimple">より画面をシンプルにする</submenu>
 </menu>
 <menu>
  <name>表示(V)</name>
  <submenu method="reflesh">チャットウィンドウをリフレッシュ</submenu>
  <submenu method="option" enabled="false">オプション</submenu>
 </menu>
 <menu>
  <name>ヘルプ(H)</name>
  <submenu method="version">バージョン情報</submenu>
 </menu>
</mainmenu>
